name: Compile Revit Plugin
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Compile Code
        run: dotnet build RfaToRvtPlugin.csproj -c Release
      - name: Download the DLL
        uses: actions/upload-artifact@v4
        with:
          name: RfaToRvtAppBundle.dll
          path: bin/Release/RfaToRvtAppBundle.dll
